---
title: "Other Data Download"
format: html
editor: visual
---

# Indicators from "Other" sources

## International Renewable Energy Agency (IRENA)

*Indicator 4244 - Public investment trends in renewable energy*

**Data source:** IRENA/Data/Finance and Investment/Renewable Energy Finance Flows

Website: <https://www.irena.org/Statistics/View-Data-by-Topic/Finance-and-Investment/Renewable-Energy-Finance-Flows>

For the report, select:

-   In the Tableau dashboard, navigate to the tab "Project Details"
-   Select: Region \[all\], Country \[all\], Technology \[all\], Year \[all\]
-   Click the "Bulk Download" link
-   Download a copy of the xlsx file

Save as: Data/Raw/other/**irena_raw.xlsx**


## International Accreditation Forum (IAF) - ISO Survey

*Indicator 1763 - ISO 14001-certified enterprises* 
*Indicator 2030 - ISO 14001-certified enterprises by economic activities* (this indicator is to be removed)
*Indicator ISO 14001-certified enterprises per billion dollars of GDP*

**Data source:** IAF/Market Intelligence (ISO Survey)/ISO Survey Data

Website: <https://www.iafcertsearch.org/analytics/iso-survey>
Note that you'll need to create a free account to access this data.

For the report, select the latest year of data:

-   Download the file with the title "1. ISO Survey 2024 results - number of certificates and sites per country and the number of sectors overall"

Save as: Data/Raw/other/**iso_raw.xlsx**


## UN Environment Programme (UNEP)

*2037 - Consumption of ozone depleting substances (ODS)*

**Data source:** UNEP/Country Data/Data Centre/Consumption of Controlled Substances

Website: <https://ozone.unep.org/countries/data>

For the report, select:

-   Choose "Data in Tables" to obtain data at a more detailed level
-   Output units: ODP tonnes or in CO2-eq tonnes
-   Party: keep as "choose some options" (keep the default select-all option)
-   Select radio button "Show individual parties"
-   Group of parties: select "Latin America and the Caribbean"
-   Annex Group: select chlorofluorocarbons (CFCs), halons, other fully halogenated CFCs, carbon tetrachloride (CTC), methyl chloroform (TCA), hydrochlorofluorocarbons (HCFCs), hydrobromofluorocarbons (HBFCs), bromochloromethane (BCM), and methyl bromide (MB). Note that this is all the substances in the list EXCEPT hydrofluorocarbons (HFCs), which are not ozone depleting.
-   Period: choose all years
-   More filters: leave these un-selected
-   Group by: select radio button "Group output by Annex group"
-   Download the Excel file for EACH annex group (substance). The result should be 9 xlsx files.
-   Rename each xlsx file in the format as follows: ods_cfc_raw.xlsx or ods_mb_raw.xlsx

Save as: Data/Raw/other/**ods_hcfc_raw.xlsx** (in this pattern, x9 files)


## Ramsar

*Indicator 2016 - Surface area of Ramsar designated wetlands*

**Data source:** Ramsar/Explore Sites

Website: <https://rsis.ramsar.org/#exports>

For the report, select:

-   Within the Ramsar site area, select the tab "Exports"
-   Select the default format as "Microsoft Excel file"
-   Enter your email for the results to be sent

Save as: Data/Raw/other/**ramsar_raw.xlsx**
